const CREATE_SESSION_FAILURE = 'CREATE_SESSION_FAILURE';
const CREATE_SESSION_REQUEST = 'CREATE_SESSION_REQUEST';
const CREATE_SESSION_SUCCESS = 'CREATE_SESSION_SUCCESS';
const FETCH_USERS = 'FETCH_USERS';

export {
  CREATE_SESSION_FAILURE,
  CREATE_SESSION_REQUEST,
  CREATE_SESSION_SUCCESS,
  FETCH_USERS,
};
