const FETCH_CARDS = 'FETCH_CARDS';
const FETCH_CARDS_FAILURE = 'FETCH_CARDS_FAILURE';
const FETCH_CARDS_SUCCESS = 'FETCH_CARDS_SUCCESS';

export {
  FETCH_CARDS,
  FETCH_CARDS_FAILURE,
  FETCH_CARDS_SUCCESS,
}