const FETCH_CARDS_REQUEST = 'FETCH_CARDS_REQUEST';
const FETCH_CARDS_FAILURE = 'FETCH_CARDS_FAILURE';
const FETCH_CARDS_SUCCESS = 'FETCH_CARDS_SUCCESS';
const FETCH_TYPES_FAILURE = 'FETCH_TYPES_FAILURE';
const FETCH_TYPES_REQUEST = 'FETCH_TYPES_REQUEST';
const FETCH_TYPES_SUCCESS = 'FETCH_TYPES_SUCCESS';
const SEARCH_CARDS_REQUEST = 'SEARCH_CARDS_REQUEST';
const SEARCH_CARDS_SUCCESS = 'SEARCH_CARDS_SUCCESS';
const SEARCH_CARDS_FAILURE = 'SEARCH_CARDS_FAILURE';

export {
  FETCH_CARDS_REQUEST,
  FETCH_CARDS_FAILURE,
  FETCH_CARDS_SUCCESS,
  FETCH_TYPES_FAILURE,
  FETCH_TYPES_REQUEST,
  FETCH_TYPES_SUCCESS,
  SEARCH_CARDS_REQUEST,
  SEARCH_CARDS_FAILURE,
  SEARCH_CARDS_SUCCESS,
}