const DELETE_DECK_SUCCESS = 'DELETE_DECK_SUCCESS';
const DELETE_DECKS_SUCCESS = 'DELETE_DECKS_SUCCESS';
const FETCH_DECKS = 'FETCH_DECKS';
const SET_SELECTED_ROW_KEYS = 'SET_SELECTED_ROW_KEYS';

export {
  DELETE_DECK_SUCCESS,
  DELETE_DECKS_SUCCESS,
  FETCH_DECKS,
  SET_SELECTED_ROW_KEYS,
};
