const ADD_CARD_TO_DECK = 'ADD_CARD_TO_DECK';
const FETCH_CARD_FAILURE = 'FETCH_CARD_FAILURE';
const FETCH_CARD_REQUEST = 'FETCH_CARD_REQUEST';
const FETCH_CARD_SUCCESS = 'FETCH_CARD_SUCCESS';
const MODAL_HIDE = 'MODAL_HIDE';
const MODAL_SHOW = 'MODAL_SHOW';

export {
  ADD_CARD_TO_DECK,
  FETCH_CARD_FAILURE,
  FETCH_CARD_REQUEST,
  FETCH_CARD_SUCCESS,
  MODAL_HIDE,
  MODAL_SHOW,
}